---

galaxy_info:
  role_name: storage_pool
  namespace: bodsch

  author: Bodo Schulz
  description: manage libvirt storage pools

  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - system
    - libvirt
    - kvm
    - storage

dependencies: []

...
