---

- name: manage monolithic services
  ansible.builtin.include_tasks: services/monolithic.yml
  when:
    - not ansible_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
    - libvirtd_version is version_compare("10", operator='<')

- name: manage modular services
  ansible.builtin.include_tasks: services/modular.yml
  when:
    - not ansible_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
    - libvirtd_version is version_compare("10", operator='>=')

...
