---

- name: manage monolithic services
  ansible.builtin.include_tasks: services/monolithic.yml
  when:
    - not ansible_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
    - not (libvirt_use_modular | bool)

- name: manage modular services
  ansible.builtin.include_tasks: services/modular.yml
  when:
    - not ansible_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
    - libvirt_use_modular | bool

...
