---

libvirt_dependecies:
  - iproute2
  - python3-lxml

libvirt_packages:
  - libvirt-daemon
  - libvirt-daemon-system
  - libvirt-dbus
  - python3-libvirt
  - python3-dbus
  - qemu-system-x86    # provides /usr/bin/qemu-system-x86_64
  - qemu-utils         # provides qemu-img

...
