---

# - name: create sysconf directory
#   ansible.builtin.file:
#     state: directory
#     path: "{{ libvirt_defaults_directory }}"
#     mode: u=rw,g=r,o=r
#
# - name: create system libvirtd config
#   become: true
#   ansible.builtin.template:
#     src: "{{ libvirt_defaults_directory[1:] }}/libvirtd.j2"
#     dest: "{{ libvirt_defaults_directory }}/libvirtd"
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r
#     backup: true
#   notify:
#     - restart {{ libvirt_service.name }}

- name: ensure dbus service are running
  ansible.builtin.service:
    name: dbus.service
    state: started
  when:
    - not ansible_check_mode

- name: merge service/socket lifecycle defaults with custom settings
  ansible.builtin.set_fact:
    libvirt_services: "{{ libvirt_defaults_services | combine(libvirt_services, recursive=True) }}"

- name: configure monolithic services
  ansible.builtin.include_tasks: configure/monolithic.yml
  when:
    - not ansible_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
    - not (libvirt_use_modular | bool)

- name: configure modular services
  ansible.builtin.include_tasks: configure/modular.yml
  when:
    - not ansible_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
    - libvirt_use_modular | bool

# Storage pools and virtual networks are handled by the dedicated
# bodsch.kvm.storage_pool and bodsch.kvm.network roles.

...
