---

- name: disable monolithic daemons
  bodsch.kvm.monolithic_services:
    state: disable
    units:
      - libvirtd.service
      - libvirtd.socket
      - libvirtd-ro.socket
      - libvirtd-admin.socket
      - libvirtd-tcp.socket
      - libvirtd-tls.socket
  notify:
    - daemon-reload

- name: enable modular daemon sockets
  bodsch.kvm.modular_services:
    state: enable
    units: "{{ libvirt_services | bodsch.kvm.modular_daemons(only_sockets=True) }}"
  notify:
    - daemon-reload

- name: enable modular daemon services
  bodsch.kvm.modular_services:
    state: enable
    units: "{{ libvirt_services | bodsch.kvm.modular_daemons(only_services=True) }}"
  notify:
    - daemon-reload

- name: remote access
  when:
    - (libvirt_proxy.listen_tls | bool) or (libvirt_proxy.listen_tcp | bool)
  block:
    - name: create units for proxy daemons
      ansible.builtin.set_fact:
        libvirt_proxy_daemons: "{{ libvirt_services | bodsch.kvm.libvirt_proxy_daemons(config=libvirt_proxy) }}"
        libvirt_proxy_daemons_service: "{{ libvirt_services | bodsch.kvm.libvirt_proxy_daemons(config=libvirt_proxy, only_services=True) }}"

    - name: enable modular proxy services
      bodsch.kvm.modular_services:
        state: enable
        units: "{{ libvirt_proxy_daemons }}"
      notify:
        - daemon-reload

    - name: start modular proxy services
      bodsch.kvm.modular_services:
        state: start
        units: "{{ libvirt_proxy_daemons_service }}"
      notify:
        - daemon-reload

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
