---

- name: enable / disable libvirtd-tcp.socket
  become: true
  ansible.builtin.service:
    name: libvirtd-tcp.socket
    enabled: "{{ 'true' if libvirt_libvirtd.enable_tcp else 'false' }}"
  failed_when: false
  notify:
    - restart libvirtd-tcp.socket
    - wait for running libvirtd
  when:
    - not ansible_check_mode
    - ansible_service_mgr | lower == "systemd"
    - libvirt_services.libvirtd.enabled

- name: enable / disable libvirtd-tls.socket
  become: true
  ansible.builtin.service:
    name: libvirtd-tls.socket
    enabled: "{{ 'true' if libvirt_libvirtd.enable_tls else 'false' }}"
  failed_when: false
  notify:
    - restart libvirtd-tls.socket
    - wait for running libvirtd
  when:
    - not ansible_check_mode
    - ansible_service_mgr | lower == "systemd"
    - libvirt_services.libvirtd.enabled

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure libvirtd is enabled on boot
  become: true
  ansible.builtin.service:
    name: "{{ libvirt_service.name }}"
    enabled: true
    state: started
  when:
    - not ansible_check_mode
    - libvirt_services.libvirtd.enabled
    - _service_states.monolithic

...
