---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: configure virtual networks
  ansible.builtin.include_tasks: configure.yml
  when:
    - virtual_networks | default([]) | count > 0

...
