---

galaxy_info:
  role_name: vm
  namespace: bodsch

  author: Bodo Schulz
  description: create and handles virtuell kvm instances

  license: Apache
  min_ansible_version: "2.12"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - system
    - libvirt
    - kvm

dependencies: []

...
