---

# device mapping
instances_root_disk_bus: "virtio"
instances_cdrom_bus: "sata"

# target device names from vdb onwards for data disks
instances_data_disk_letters: ["b", "c", "d", "e", "f", "g", "h", "i"]

...
