---

- name: prepare
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_facts.distribution | lower == 'archlinux' or
          ansible_facts.os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm
          register: pacman
          changed_when: pacman.rc != 0
          failed_when: pacman.rc != 0

    - name: update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

  # base_images imports into an existing pool -> provision libvirt + the pool first.
  roles:
    - role: bodsch.kvm.libvirt
    - role: bodsch.kvm.storage_pool

...
