#!/usr/bin/python3
# -*- coding: utf-8 -*-

# (c) 2026, Bodo Schulz <bodo@boone-schulz.de>
# Apache-2.0 (see LICENSE or https://opensource.org/license/apache-2-0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

DOCUMENTATION = r"""
---
module: libvirt_domain
author: Bodo Schulz (@bodsch)
version_added: "0.1.0"
short_description: Manage a set of libvirt domains (VMs) from structured parameters.
description:
  - Defines libvirt domains and reconciles their run state.
  - A clean, validated replacement for the C(define) command and run-state
    handling of C(community.libvirt.virt) - the common case (memory, vcpus,
    file disks, network interfaces, graphics, console, rng) is described by
    typed parameters instead of a freestyle C(xml) block.
  - For configurations outside that subset, a per-domain C(raw_xml) escape
    hatch accepts a full C(<domain>) definition.
  - Defining an existing domain is idempotent - the module carries the existing
    UUID and interface MAC addresses into the new definition and compares the
    resulting inactive XML to decide whether anything actually changed.
  - Takes a list of domains and reconciles all of them in a single task, so
    playbooks do not need C(loop).
options:
  uri:
    description:
      - libvirt connection URI.
    type: str
    default: "qemu:///system"
  domains:
    description:
      - List of domains to reconcile.
    type: list
    elements: dict
    required: true
    suboptions:
      name:
        description:
          - Domain name.
        type: str
        required: true
      state:
        description:
          - C(present) defines the domain and leaves its run state untouched.
          - C(running) defines and starts (or resumes) the domain.
          - C(shutdown) requests a graceful ACPI shutdown of a running domain.
          - C(paused) suspends a running domain.
          - C(destroyed) forces a running domain off.
          - C(absent) destroys (if running) and undefines the domain.
        type: str
        choices: [present, running, shutdown, paused, destroyed, absent]
        default: present
      memory_mb:
        description:
          - Memory in MiB. Required for a structured definition.
        type: int
      vcpus:
        description:
          - Number of virtual CPUs. Required for a structured definition.
        type: int
      domain_type:
        description:
          - Domain hypervisor type.
        type: str
        choices: [kvm, qemu]
        default: kvm
      arch:
        description:
          - CPU architecture of the guest.
        type: str
        default: x86_64
      machine:
        description:
          - Machine type (e.g. C(q35)). Left to libvirt's default when omitted.
        type: str
      features:
        description:
          - Simple toggle CPU features to enable.
        type: list
        elements: str
        default: [acpi, apic]
      disks:
        description:
          - File-backed disks attached to the domain.
        type: list
        elements: dict
        suboptions:
          source:
            description: Absolute path of the backing file.
            type: str
            required: true
          target_dev:
            description: Guest device name (e.g. C(vda), C(sda)).
            type: str
            required: true
          device:
            description: Disk device kind.
            type: str
            choices: [disk, cdrom]
            default: disk
          bus:
            description: Target bus.
            type: str
            choices: [virtio, sata, ide, scsi, usb]
            default: virtio
          format:
            description:
              - Driver format. Defaults to C(qcow2) for disks and C(raw) for
                cdrom devices.
            type: str
          readonly:
            description:
              - Mark the disk read-only. Defaults to V(true) for cdrom devices.
            type: bool
      interfaces:
        description:
          - Network interfaces attached to the domain.
        type: list
        elements: dict
        suboptions:
          type:
            description: Interface type.
            type: str
            choices: [network, bridge]
            default: network
          source:
            description:
              - Source name - the libvirt network (C(type=network)) or host
                bridge (C(type=bridge)).
            type: str
            required: true
          model:
            description: NIC model.
            type: str
            default: virtio
          mac:
            description:
              - Explicit MAC address. Generated by libvirt (and kept stable
                across runs) when omitted.
            type: str
      graphics:
        description:
          - Graphics device. Omit, or set C(type=none), for a headless domain.
        type: dict
        suboptions:
          type:
            description: Graphics backend.
            type: str
            choices: [vnc, spice, none]
            required: true
          autoport:
            description: Let libvirt allocate the port automatically.
            type: bool
            default: true
          listen:
            description: Listen address.
            type: str
      console:
        description:
          - Attach a virtio pty console.
        type: bool
        default: true
      rng:
        description:
          - Attach a virtio RNG backed by C(/dev/urandom).
        type: bool
        default: true
      autostart:
        description:
          - Whether the domain starts automatically on host boot. Left
            untouched when omitted.
        type: bool
      uuid:
        description:
          - Explicit domain UUID. Generated by libvirt (and kept stable across
            runs) when omitted.
        type: str
      raw_xml:
        description:
          - Full C(<domain>) XML definition, used verbatim instead of the
            structured parameters. Mutually exclusive with the structured
            definition fields. The domain C(name) is enforced to match.
        type: str
requirements:
  - libvirt-python
notes:
  - Supports C(check_mode). For an already-defined domain, check mode reports
    run-state and autostart changes but cannot reliably predict definition
    changes without redefining, so it reports the definition as unchanged.
  - Domain names should be unique within a single call; the per-domain results
    are keyed by name.
"""

EXAMPLES = r"""
- name: define and run an instance
  bodsch.kvm.libvirt_domain:
    domains:
      - name: web01
        state: running
        memory_mb: 2048
        vcpus: 2
        disks:
          - source: /var/lib/libvirt/images/web01-os.qcow2
            target_dev: vda
          - source: /var/lib/libvirt/images/web01-cidata.iso
            target_dev: sda
            device: cdrom
            bus: sata
        interfaces:
          - source: bridge_network
        graphics:
          type: spice
        autostart: true

- name: remove an instance
  bodsch.kvm.libvirt_domain:
    domains:
      - name: web01
        state: absent
"""

RETURN = r"""
changed:
  description: Whether any domain was defined, changed, started, stopped or removed.
  returned: always
  type: bool
failed:
  description: Whether reconciling any domain failed.
  returned: always
  type: bool
state:
  description: Per-domain result, one entry per requested domain keyed by name.
  returned: always
  type: list
  elements: dict
domains:
  description:
    - Resolved facts for each domain that exists after reconciliation, keyed by
      domain name.
  returned: always
  type: dict
  sample:
    web01:
      uuid: "a1b2c3d4-0000-0000-0000-000000000000"
      active: true
      autostart: true
      persistent: true
      run_state: running
"""

import traceback
import xml.etree.ElementTree as ET

from ansible.module_utils.basic import AnsibleModule, missing_required_lib
from ansible_collections.bodsch.core.plugins.module_utils.module_results import results
from ansible_collections.bodsch.kvm.plugins.module_utils.libvirt_connection import (
    HAS_LIBVIRT,
    LIBVIRT_IMPORT_ERROR,
    LibvirtConnection,
    LibvirtConnectionError,
)
from ansible_collections.bodsch.kvm.plugins.module_utils.libvirt_xml import (
    DOMAIN_STATE_NAMES,
    DomainXMLBuilder,
    XMLValidationError,
)

if HAS_LIBVIRT:
    import libvirt

DOMAIN_FACT_KEYS = ("uuid", "active", "autostart", "persistent", "run_state")

# structured fields that must not be combined with raw_xml
RAW_XML_CONFLICTS = ("memory_mb", "vcpus", "disks", "interfaces", "graphics", "machine", "uuid")


class LibvirtDomain:
    """Reconcile a list of libvirt domains against the requested state."""

    def __init__(self, module):
        """ """
        self.module = module

        self.uri = module.params.get("uri")
        self.domains = module.params.get("domains")

    def run(self):
        """ """
        result_state = []
        domains_facts = {}

        try:
            with LibvirtConnection(self.uri) as conn:
                for spec in self.domains:
                    name = spec.get("name")
                    try:
                        entry = self._reconcile_one(conn, spec)
                    except (LibvirtConnectionError, XMLValidationError) as e:
                        entry = dict(changed=False, failed=True, msg=str(e))
                    except libvirt.libvirtError as e:
                        entry = dict(changed=False, failed=True, msg=f"libvirt error: {e.get_error_message()}")

                    result_state.append({name: entry})

                    facts = {k: entry[k] for k in DOMAIN_FACT_KEYS if k in entry}
                    if facts:
                        domains_facts[name] = facts

        except LibvirtConnectionError as e:
            # connection-level failure affects every domain: fail hard.
            self.module.fail_json(msg=str(e))

        _, has_changed, has_failed, _, _, _ = results(self.module, result_state)

        return dict(
            changed=has_changed,
            failed=has_failed,
            state=result_state,
            domains=domains_facts,
        )

    # -- dispatch ----------------------------------------------------------

    def _reconcile_one(self, conn, spec):
        """Reconcile one domain spec against its current state."""
        name = spec.get("name")
        state = spec.get("state")

        self._validate_spec(spec)

        existing = conn.lookup_domain(name)

        if state == "absent":
            return self._absent_one(existing)

        msgs = []

        incoming_xml = self._build_xml(spec)
        dom, define_changed = self._define(conn, existing, incoming_xml)

        if define_changed:
            msgs.append("created" if existing is None else "definition updated")

        if dom is None:
            # check_mode and the domain does not exist yet
            return dict(changed=True, msg="would define domain")

        changed = define_changed
        changed = self._apply_autostart(dom, spec, msgs) or changed
        changed = self._apply_run_state(dom, state, msgs) or changed

        entry = dict(changed=changed, msg=", ".join(msgs) or "ok")
        entry.update(self._domain_facts(dom))
        return entry

    # -- validation / XML --------------------------------------------------

    def _validate_spec(self, spec):
        """Enforce the raw_xml / structured-fields contract."""
        name = spec.get("name")

        if spec.get("raw_xml"):
            conflicts = [k for k in RAW_XML_CONFLICTS if spec.get(k)]
            if conflicts:
                raise XMLValidationError(
                    f"domain '{name}': 'raw_xml' is mutually exclusive with {conflicts}"
                )
        elif spec.get("memory_mb") is None or spec.get("vcpus") is None:
            raise XMLValidationError(
                f"domain '{name}': a structured definition requires 'memory_mb' and 'vcpus' "
                f"(or provide 'raw_xml')"
            )

    def _build_xml(self, spec):
        """Return the incoming domain XML, from raw_xml or the structured builder."""
        raw = spec.get("raw_xml")
        if raw:
            return self._prepare_raw(spec, raw)

        builder = DomainXMLBuilder(
            name=spec.get("name"),
            memory_mb=spec.get("memory_mb"),
            vcpus=spec.get("vcpus"),
            disks=spec.get("disks"),
            interfaces=spec.get("interfaces"),
            domain_type=spec.get("domain_type"),
            arch=spec.get("arch"),
            machine=spec.get("machine"),
            features=spec.get("features"),
            graphics=spec.get("graphics"),
            console=spec.get("console"),
            rng=spec.get("rng"),
            uuid=spec.get("uuid"),
        )
        return builder.to_xml()

    def _prepare_raw(self, spec, raw):
        """Validate the raw XML and pin its <name> to the requested domain name."""
        try:
            root = ET.fromstring(raw)
        except ET.ParseError as e:
            raise XMLValidationError(f"raw_xml is not well-formed XML: {e}")

        if root.tag != "domain":
            raise XMLValidationError("raw_xml root element must be <domain>")

        name_el = root.find("name")
        if name_el is None:
            name_el = ET.Element("name")
            root.insert(0, name_el)
        name_el.text = spec.get("name")

        return ET.tostring(root, encoding="unicode")

    # -- define (idempotent) ----------------------------------------------

    def _define(self, conn, existing, incoming_xml):
        """
        Define the domain, carrying over the existing UUID and interface MAC
        addresses, and report whether the inactive definition actually changed.

        Returns ``(domain, changed)``. In check mode a non-existent domain
        returns ``(None, True)`` (would create); an existing domain returns
        ``(existing, False)`` since the definition cannot be diffed without
        redefining it.
        """
        incoming = ET.fromstring(incoming_xml)

        existing_inactive_raw = None
        if existing is not None:
            existing_inactive_raw = existing.XMLDesc(libvirt.VIR_DOMAIN_XML_INACTIVE)
            self._carry_over_identity(incoming, existing, existing_inactive_raw)

        if self.module.check_mode:
            if existing is None:
                return None, True
            return existing, False

        dom = conn.define_domain(ET.tostring(incoming, encoding="unicode"))

        if existing is None:
            return dom, True

        new_inactive = dom.XMLDesc(libvirt.VIR_DOMAIN_XML_INACTIVE)
        return dom, (existing_inactive_raw != new_inactive)

    def _carry_over_identity(self, incoming, existing, existing_inactive_raw):
        """Copy the existing UUID and interface MACs into the incoming XML."""
        existing_root = ET.fromstring(existing_inactive_raw)
        existing_uuid = existing.UUIDString()

        incoming_uuid = incoming.findtext("uuid")
        if incoming_uuid and incoming_uuid != existing_uuid:
            raise XMLValidationError(
                f"refusing to redefine domain '{incoming.findtext('name')}' with a "
                f"different UUID (existing {existing_uuid}, requested {incoming_uuid})"
            )

        if not incoming_uuid:
            uuid_el = ET.Element("uuid")
            uuid_el.text = existing_uuid
            incoming.insert(1, uuid_el)

        existing_ifaces = existing_root.findall("./devices/interface")
        incoming_ifaces = incoming.findall("./devices/interface")

        for index, iface in enumerate(incoming_ifaces):
            if iface.find("mac") is not None or index >= len(existing_ifaces):
                continue
            existing_mac = existing_ifaces[index].find("mac")
            if existing_mac is not None and existing_mac.get("address"):
                iface.insert(0, ET.Element("mac", {"address": existing_mac.get("address")}))

    # -- run state / autostart --------------------------------------------

    def _apply_autostart(self, dom, spec, msgs):
        """Enforce the autostart flag if the spec requests one."""
        autostart = spec.get("autostart")
        if autostart is None:
            return False

        if bool(dom.autostart()) == autostart:
            return False

        if not self.module.check_mode:
            dom.setAutostart(1 if autostart else 0)
        msgs.append(f"autostart={autostart}")
        return True

    def _apply_run_state(self, dom, state, msgs):
        """Drive the domain towards the requested run state."""
        if state == "present":
            return False

        active = bool(dom.isActive())
        state_id = dom.state()[0] if active else None

        if state == "running":
            if not active:
                self._do(dom.create)
                msgs.append("started")
                return True
            if state_id == libvirt.VIR_DOMAIN_PAUSED:
                self._do(dom.resume)
                msgs.append("resumed")
                return True
            return False

        if state == "paused":
            if active and state_id == libvirt.VIR_DOMAIN_RUNNING:
                self._do(dom.suspend)
                msgs.append("paused")
                return True
            return False

        if state == "shutdown":
            if active:
                self._do(dom.shutdown)
                msgs.append("shutdown requested")
                return True
            return False

        if state == "destroyed":
            if active:
                self._do(dom.destroy)
                msgs.append("destroyed")
                return True
            return False

        return False

    def _absent_one(self, existing):
        """Ensure the domain is destroyed (if running) and undefined."""
        if existing is None:
            return dict(changed=False, msg="already absent")

        if self.module.check_mode:
            return dict(changed=True, msg="would undefine domain")

        if bool(existing.isActive()):
            existing.destroy()

        existing.undefine()

        return dict(changed=True, msg="undefined")

    # -- helpers -----------------------------------------------------------

    def _do(self, fn):
        """Run a libvirt mutation unless in check mode."""
        if not self.module.check_mode:
            fn()

    def _domain_facts(self, dom):
        """ """
        state_id = dom.state()[0]
        return dict(
            uuid=dom.UUIDString(),
            active=bool(dom.isActive()),
            autostart=bool(dom.autostart()),
            persistent=bool(dom.isPersistent()),
            run_state=DOMAIN_STATE_NAMES.get(state_id, "unknown"),
        )


def main():
    """ """
    domain_suboptions = dict(
        name=dict(type="str", required=True),
        state=dict(type="str", default="present", choices=["present", "running", "shutdown", "paused", "destroyed", "absent"]),
        memory_mb=dict(type="int"),
        vcpus=dict(type="int"),
        domain_type=dict(type="str", default="kvm", choices=["kvm", "qemu"]),
        arch=dict(type="str", default="x86_64"),
        machine=dict(type="str"),
        features=dict(type="list", elements="str", default=["acpi", "apic"]),
        disks=dict(
            type="list",
            elements="dict",
            options=dict(
                source=dict(type="str", required=True),
                target_dev=dict(type="str", required=True),
                device=dict(type="str", default="disk", choices=["disk", "cdrom"]),
                bus=dict(type="str", default="virtio", choices=["virtio", "sata", "ide", "scsi", "usb"]),
                format=dict(type="str"),
                readonly=dict(type="bool"),
            ),
        ),
        interfaces=dict(
            type="list",
            elements="dict",
            options=dict(
                type=dict(type="str", default="network", choices=["network", "bridge"]),
                source=dict(type="str", required=True),
                model=dict(type="str", default="virtio"),
                mac=dict(type="str"),
            ),
        ),
        graphics=dict(
            type="dict",
            options=dict(
                type=dict(type="str", required=True, choices=["vnc", "spice", "none"]),
                autoport=dict(type="bool", default=True),
                listen=dict(type="str"),
            ),
        ),
        console=dict(type="bool", default=True),
        rng=dict(type="bool", default=True),
        autostart=dict(type="bool"),
        uuid=dict(type="str"),
        raw_xml=dict(type="str"),
    )

    args = dict(
        uri=dict(type="str", default="qemu:///system"),
        domains=dict(
            type="list",
            elements="dict",
            required=True,
            options=domain_suboptions,
        ),
    )

    module = AnsibleModule(
        argument_spec=args,
        supports_check_mode=True,
    )

    if not HAS_LIBVIRT:
        module.fail_json(
            msg=missing_required_lib("libvirt-python"),
            exception=LIBVIRT_IMPORT_ERROR,
        )

    try:
        d = LibvirtDomain(module)
        result = d.run()
    except Exception as e:  # pragma: no cover - defensive
        module.fail_json(msg=f"unexpected error: {e}", exception=traceback.format_exc())

    module.exit_json(**result)


# import module snippets
if __name__ == "__main__":
    main()
