#!/usr/bin/python3
# -*- coding: utf-8 -*-

# (c) 2026, Bodo Schulz <bodo@boone-schulz.de>
# Apache-2.0 (see LICENSE or https://opensource.org/license/apache-2-0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

DOCUMENTATION = r"""
---
module: libvirt_network
author: Bodo Schulz (@bodsch)
version_added: "0.1.0"
short_description: Manage a set of libvirt virtual networks from structured parameters.
description:
  - Defines, starts, stops and removes libvirt virtual networks.
  - A clean, validated replacement for C(community.libvirt.virt_net) - each
    network is described by typed parameters (mode, bridge, DHCP, DNS, VLAN
    portgroups) instead of a freestyle C(xml) block, and the XML is built and
    validated by the module before it reaches the hypervisor.
  - Takes a list of network definitions and reconciles all of them in a single
    task, so playbooks do not need C(loop).
options:
  uri:
    description:
      - libvirt connection URI.
    type: str
    default: "qemu:///system"
  networks:
    description:
      - List of virtual networks to reconcile.
    type: list
    elements: dict
    required: true
    suboptions:
      name:
        description:
          - Name of the virtual network.
        type: str
        required: true
      state:
        description:
          - C(present) ensures the network is defined but leaves its run state
            untouched.
          - C(active) ensures the network is defined and running.
          - C(inactive) ensures the network is defined and stopped.
          - C(absent) ensures the network is stopped and undefined.
        type: str
        choices: [present, active, inactive, absent]
        default: present
      mode:
        description:
          - Forwarding mode. C(private) creates an isolated network (a bridge
            with no forward). Omit for a libvirt-managed isolated network.
        type: str
        choices: [nat, route, bridge, private]
      bridge_name:
        description:
          - Name of the bridge device. Required when C(mode) is set.
        type: str
      route_device:
        description:
          - Host device to route through. Required when C(mode=route).
        type: str
      virtualport_type:
        description:
          - Virtual port type (e.g. C(openvswitch)).
        type: str
      domain:
        description:
          - DNS domain name announced for this network.
        type: str
      dns:
        description:
          - DNS configuration for the network.
        type: dict
        suboptions:
          forwarders:
            description:
              - List of upstream DNS forwarder IPv4 addresses.
            type: list
            elements: str
            default: []
      dhcp:
        description:
          - IPv4 DHCP configuration. When given, defines the network's C(ip)
            and DHCP range.
        type: dict
        suboptions:
          gateway:
            description: Gateway / network interface address.
            type: str
            required: true
          netmask:
            description: Network mask (e.g. V(255.255.255.0)).
            type: str
            required: true
          range_start:
            description: First address of the DHCP range.
            type: str
            required: true
          range_end:
            description: Last address of the DHCP range.
            type: str
            required: true
      vlan_tag:
        description:
          - Network-wide VLAN tag (0-4095).
        type: int
      vlans:
        description:
          - VLAN portgroups for this network.
        type: list
        elements: dict
        suboptions:
          name:
            description: Portgroup name.
            type: str
            required: true
          default:
            description: Whether this is the default portgroup.
            type: bool
            default: false
          trunk:
            description: Whether this portgroup is a VLAN trunk.
            type: bool
            default: false
          tags:
            description:
              - VLAN tags. A non-trunk portgroup may carry at most one tag; a
                trunk requires at least one.
            type: list
            elements: int
            default: []
      autostart:
        description:
          - Whether the network starts automatically on host boot. Left
            untouched when omitted.
        type: bool
      uuid:
        description:
          - Explicit network UUID. Generated by libvirt when omitted.
        type: str
requirements:
  - libvirt-python
notes:
  - Supports C(check_mode).
  - An existing network's definition is never rewritten; the definition
    parameters only apply when the network is first defined.
  - Network names should be unique within a single call; the per-network
    results are keyed by name.
"""

EXAMPLES = r"""
- name: define, activate and autostart networks in one task
  bodsch.kvm.libvirt_network:
    networks:
      - name: nat0
        state: active
        mode: nat
        bridge_name: virbr10
        domain: matrix.lan
        dns:
          forwarders: ["192.168.10.1", "1.1.1.1"]
        dhcp:
          gateway: 192.168.10.1
          netmask: 255.255.255.0
          range_start: 192.168.10.50
          range_end: 192.168.10.200
        autostart: true
      - name: legacy
        state: absent
"""

RETURN = r"""
changed:
  description: Whether any network was defined, started, stopped or removed.
  returned: always
  type: bool
failed:
  description: Whether reconciling any network failed.
  returned: always
  type: bool
state:
  description: Per-network result, one entry per requested network keyed by name.
  returned: always
  type: list
  elements: dict
networks:
  description:
    - Resolved facts for each network that exists after reconciliation, keyed
      by network name.
  returned: always
  type: dict
  sample:
    nat0:
      bridge: virbr10
      active: true
      autostart: true
      persistent: true
      uuid: "a1b2c3d4-0000-0000-0000-000000000000"
"""

import traceback

from ansible.module_utils.basic import AnsibleModule, missing_required_lib
from ansible_collections.bodsch.core.plugins.module_utils.module_results import results
from ansible_collections.bodsch.kvm.plugins.module_utils.libvirt_connection import (
    HAS_LIBVIRT,
    LIBVIRT_IMPORT_ERROR,
    LibvirtConnection,
    LibvirtConnectionError,
)
from ansible_collections.bodsch.kvm.plugins.module_utils.libvirt_xml import (
    NetworkXMLBuilder,
    XMLValidationError,
)

if HAS_LIBVIRT:
    import libvirt

NETWORK_FACT_KEYS = ("bridge", "active", "autostart", "persistent", "uuid")


class LibvirtNetwork:
    """Reconcile a list of libvirt virtual networks against the requested state."""

    def __init__(self, module):
        """ """
        self.module = module

        self.uri = module.params.get("uri")
        self.networks = module.params.get("networks")

    def run(self):
        """ """
        result_state = []
        networks_facts = {}

        try:
            with LibvirtConnection(self.uri) as conn:
                for spec in self.networks:
                    name = spec.get("name")
                    try:
                        entry = self._reconcile_one(conn, spec)
                    except (LibvirtConnectionError, XMLValidationError) as e:
                        entry = dict(changed=False, failed=True, msg=str(e))
                    except libvirt.libvirtError as e:
                        entry = dict(changed=False, failed=True, msg=f"libvirt error: {e.get_error_message()}")

                    result_state.append({name: entry})

                    facts = {k: entry[k] for k in NETWORK_FACT_KEYS if k in entry}
                    if facts:
                        networks_facts[name] = facts

        except LibvirtConnectionError as e:
            # connection-level failure affects every network: fail hard.
            self.module.fail_json(msg=str(e))

        _, has_changed, has_failed, _, _, _ = results(self.module, result_state)

        return dict(
            changed=has_changed,
            failed=has_failed,
            state=result_state,
            networks=networks_facts,
        )

    # -- dispatch ----------------------------------------------------------

    def _reconcile_one(self, conn, spec):
        """Reconcile one network spec against its current state."""
        name = spec.get("name")
        state = spec.get("state")

        net = conn.lookup_network(name)

        if state == "absent":
            return self._absent_one(net)

        changed = False
        msgs = []

        if net is None:
            if self.module.check_mode:
                return dict(changed=True, msg="would define network")

            net = self._define(conn, spec)
            changed = True
            msgs.append("defined")

        changed = self._apply_autostart(net, spec, msgs) or changed
        changed = self._apply_run_state(net, state, msgs) or changed

        entry = dict(changed=changed, msg=", ".join(msgs) or "ok")
        entry.update(self._network_facts(net))
        return entry

    # -- building blocks ---------------------------------------------------

    def _define(self, conn, spec):
        """Define a network from structured parameters."""
        builder = NetworkXMLBuilder(
            name=spec.get("name"),
            mode=spec.get("mode"),
            bridge_name=spec.get("bridge_name"),
            route_device=spec.get("route_device"),
            virtualport_type=spec.get("virtualport_type"),
            domain=spec.get("domain"),
            dns=spec.get("dns"),
            dhcp=spec.get("dhcp"),
            vlan_tag=spec.get("vlan_tag"),
            vlans=spec.get("vlans"),
            uuid=spec.get("uuid"),
        )
        return conn.define_network(builder.to_xml())

    def _apply_autostart(self, net, spec, msgs):
        """Enforce the autostart flag if the spec requests one."""
        autostart = spec.get("autostart")
        if autostart is None:
            return False

        if bool(net.autostart()) == autostart:
            return False

        if not self.module.check_mode:
            net.setAutostart(1 if autostart else 0)
        msgs.append(f"autostart={autostart}")
        return True

    def _apply_run_state(self, net, state, msgs):
        """Start or stop the network to match C(active)/C(inactive)."""
        active = bool(net.isActive())

        if state == "active" and not active:
            if not self.module.check_mode:
                net.create()
            msgs.append("started")
            return True

        if state == "inactive" and active:
            if not self.module.check_mode:
                net.destroy()
            msgs.append("stopped")
            return True

        return False

    def _absent_one(self, net):
        """Ensure the network is stopped and undefined."""
        if net is None:
            return dict(changed=False, msg="already absent")

        if self.module.check_mode:
            return dict(changed=True, msg="would undefine network")

        if bool(net.isActive()):
            net.destroy()

        net.undefine()

        return dict(changed=True, msg="undefined")

    # -- helpers -----------------------------------------------------------

    def _network_facts(self, net):
        """ """
        try:
            bridge = net.bridgeName()
        except libvirt.libvirtError:
            bridge = None

        return dict(
            bridge=bridge,
            active=bool(net.isActive()),
            autostart=bool(net.autostart()),
            persistent=bool(net.isPersistent()),
            uuid=net.UUIDString(),
        )


def main():
    """ """
    network_suboptions = dict(
        name=dict(type="str", required=True),
        state=dict(type="str", default="present", choices=["present", "active", "inactive", "absent"]),
        mode=dict(type="str", choices=["nat", "route", "bridge", "private"]),
        bridge_name=dict(type="str"),
        route_device=dict(type="str"),
        virtualport_type=dict(type="str"),
        domain=dict(type="str"),
        dns=dict(
            type="dict",
            options=dict(
                forwarders=dict(type="list", elements="str", default=[]),
            ),
        ),
        dhcp=dict(
            type="dict",
            options=dict(
                gateway=dict(type="str", required=True),
                netmask=dict(type="str", required=True),
                range_start=dict(type="str", required=True),
                range_end=dict(type="str", required=True),
            ),
        ),
        vlan_tag=dict(type="int"),
        vlans=dict(
            type="list",
            elements="dict",
            options=dict(
                name=dict(type="str", required=True),
                default=dict(type="bool", default=False),
                trunk=dict(type="bool", default=False),
                tags=dict(type="list", elements="int", default=[]),
            ),
        ),
        autostart=dict(type="bool"),
        uuid=dict(type="str"),
    )

    args = dict(
        uri=dict(type="str", default="qemu:///system"),
        networks=dict(
            type="list",
            elements="dict",
            required=True,
            options=network_suboptions,
            required_if=[
                ["mode", "nat", ["bridge_name"]],
                ["mode", "bridge", ["bridge_name"]],
                ["mode", "private", ["bridge_name"]],
                ["mode", "route", ["bridge_name", "route_device"]],
            ],
        ),
    )

    module = AnsibleModule(
        argument_spec=args,
        supports_check_mode=True,
    )

    if not HAS_LIBVIRT:
        module.fail_json(
            msg=missing_required_lib("libvirt-python"),
            exception=LIBVIRT_IMPORT_ERROR,
        )

    try:
        n = LibvirtNetwork(module)
        result = n.run()
    except Exception as e:  # pragma: no cover - defensive
        module.fail_json(msg=f"unexpected error: {e}", exception=traceback.format_exc())

    module.exit_json(**result)


# import module snippets
if __name__ == "__main__":
    main()
