#!/usr/bin/python3
# -*- coding: utf-8 -*-

# (c) 2026, Bodo Schulz <bodo@boone-schulz.de>
# Apache-2.0 (see LICENSE or https://opensource.org/license/apache-2-0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

import traceback

from ansible.module_utils.basic import AnsibleModule, missing_required_lib
from ansible_collections.bodsch.core.plugins.module_utils.module_results import results
from ansible_collections.bodsch.kvm.plugins.module_utils.libvirt_connection import (
    HAS_LIBVIRT,
    LIBVIRT_IMPORT_ERROR,
    LibvirtConnection,
    LibvirtConnectionError,
)
from ansible_collections.bodsch.kvm.plugins.module_utils.libvirt_xml import (
    PoolXMLBuilder,
    XMLValidationError,
    pool_target_path,
)

DOCUMENTATION = r"""
---
module: libvirt_pool
author: Bodo Schulz (@bodsch)
version_added: "0.1.0"
short_description: Manage a set of libvirt storage pools from structured parameters.
description:
  - Defines, starts, stops, refreshes and removes libvirt storage pools.
  - A clean, validated replacement for C(community.libvirt.virt_pool) - each
    pool is described by typed parameters instead of a freestyle C(xml) block,
    the XML is built and validated by the module, and the resolved target path
    of every pool is returned directly so playbooks no longer have to parse the
    pool XML to discover its directory.
  - Takes a list of pool definitions and reconciles all of them in a single
    task, so playbooks do not need C(loop).
options:
  uri:
    description:
      - libvirt connection URI.
    type: str
    default: "qemu:///system"
  pools:
    description:
      - List of storage pools to reconcile.
    type: list
    elements: dict
    required: true
    suboptions:
      name:
        description:
          - Name of the storage pool.
        type: str
        required: true
      state:
        description:
          - C(present) ensures the pool is defined (created from the given
            parameters if missing) but leaves its run state untouched.
          - C(active) ensures the pool is defined and running.
          - C(inactive) ensures the pool is defined and stopped.
          - C(absent) ensures the pool is stopped and undefined.
        type: str
        choices: [present, active, inactive, absent]
        default: present
      type:
        description:
          - Storage pool type. Only directory pools are currently supported.
        type: str
        choices: [dir]
        default: dir
      target_path:
        description:
          - Absolute path of the pool target directory.
          - Required to define a pool that does not exist yet; ignored when the
            pool already exists (the definition is not rewritten).
        type: path
        aliases: [path]
      mode:
        description:
          - Octal permission of the target directory (e.g. V(0755)).
        type: str
      owner:
        description:
          - Numeric owner (uid) of the target directory.
        type: str
      group:
        description:
          - Numeric group (gid) of the target directory.
        type: str
      uuid:
        description:
          - Explicit pool UUID. Generated by libvirt when omitted.
        type: str
      autostart:
        description:
          - Whether the pool starts automatically on host boot. Left untouched
            when omitted.
        type: bool
      build:
        description:
          - Build the pool target (create the directory) right after defining a
            new pool. Existing pools are never rebuilt.
        type: bool
        default: false
      refresh:
        description:
          - Refresh the pool (rescan its volumes) when it is active. Useful
            after files were added to the directory outside libvirt.
        type: bool
        default: false
requirements:
  - libvirt-python
notes:
  - Supports C(check_mode).
  - An existing pool's definition is never rewritten; C(target_path) and
    permissions only apply when the pool is first defined.
  - Pool names should be unique within a single call; the per-pool results are
    keyed by name.
"""

EXAMPLES = r"""
- name: define, activate and autostart the storage pools in one task
  bodsch.kvm.libvirt_pool:
    pools:
      - name: default
        state: active
        target_path: /var/lib/libvirt/images
        mode: "0711"
        autostart: true
      - name: scratch
        state: absent

- name: ensure a pool is active and read its target path
  bodsch.kvm.libvirt_pool:
    pools:
      - name: default
        state: active
  register: pool_result

- name: use the resolved pool path
  ansible.builtin.debug:
    var: pool_result.pools.default.path
"""

RETURN = r"""
changed:
  description: Whether any pool was defined, started, stopped, refreshed or removed.
  returned: always
  type: bool
failed:
  description: Whether reconciling any pool failed.
  returned: always
  type: bool
state:
  description: Per-pool result, one entry per requested pool keyed by name.
  returned: always
  type: list
  elements: dict
pools:
  description:
    - Resolved facts for each pool that exists after reconciliation, keyed by
      pool name.
  returned: always
  type: dict
  sample:
    default:
      path: /var/lib/libvirt/images
      active: true
      autostart: true
      persistent: true
      uuid: "a1b2c3d4-0000-0000-0000-000000000000"
"""

if HAS_LIBVIRT:
    import libvirt

POOL_FACT_KEYS = ("path", "active", "autostart", "persistent", "uuid")


class LibvirtPool:
    """Reconcile a list of libvirt storage pools against the requested state."""

    def __init__(self, module):
        """ """
        self.module = module

        self.uri = module.params.get("uri")
        self.pools = module.params.get("pools")

    def run(self):
        """ """
        result_state = []
        pools_facts = {}

        try:
            with LibvirtConnection(self.uri) as conn:
                for spec in self.pools:
                    name = spec.get("name")
                    try:
                        entry = self._reconcile_one(conn, spec)
                    except (LibvirtConnectionError, XMLValidationError) as e:
                        entry = dict(changed=False, failed=True, msg=str(e))
                    except libvirt.libvirtError as e:
                        entry = dict(changed=False, failed=True, msg=f"libvirt error: {e.get_error_message()}")

                    result_state.append({name: entry})

                    facts = {k: entry[k] for k in POOL_FACT_KEYS if k in entry}
                    if facts:
                        pools_facts[name] = facts

        except LibvirtConnectionError as e:
            # connection-level failure affects every pool: fail hard.
            self.module.fail_json(msg=str(e))

        _, has_changed, has_failed, _, _, _ = results(self.module, result_state)

        return dict(
            changed=has_changed,
            failed=has_failed,
            state=result_state,
            pools=pools_facts,
        )

    # -- dispatch ----------------------------------------------------------

    def _reconcile_one(self, conn, spec):
        """Reconcile one pool spec against its current state."""
        name = spec.get("name")
        state = spec.get("state")

        pool = conn.lookup_pool(name)

        if state == "absent":
            return self._absent_one(pool)

        changed = False
        msgs = []

        if pool is None:
            target_path = spec.get("target_path")
            if not target_path:
                return dict(
                    changed=False,
                    failed=True,
                    msg=f"pool '{name}' does not exist and no 'target_path' was given to define it",
                )

            if self.module.check_mode:
                return dict(changed=True, msg="would define pool", path=target_path)

            pool = self._define(conn, spec)
            changed = True
            msgs.append("defined")

        changed = self._apply_autostart(pool, spec, msgs) or changed
        changed = self._apply_run_state(pool, state, msgs) or changed
        changed = self._apply_refresh(pool, spec, msgs) or changed

        entry = dict(changed=changed, msg=", ".join(msgs) or "ok")
        entry.update(self._pool_facts(pool))
        return entry

    # -- building blocks ---------------------------------------------------

    def _define(self, conn, spec):
        """Define a pool from structured parameters and optionally build it."""
        builder = PoolXMLBuilder(
            name=spec.get("name"),
            target_path=spec.get("target_path"),
            pool_type=spec.get("type"),
            mode=spec.get("mode"),
            owner=spec.get("owner"),
            group=spec.get("group"),
            uuid=spec.get("uuid"),
        )
        pool = conn.define_pool(builder.to_xml())

        if spec.get("build"):
            pool.build(0)

        return pool

    def _apply_autostart(self, pool, spec, msgs):
        """Enforce the autostart flag if the spec requests one."""
        autostart = spec.get("autostart")
        if autostart is None:
            return False

        if bool(pool.autostart()) == autostart:
            return False

        if not self.module.check_mode:
            pool.setAutostart(1 if autostart else 0)
        msgs.append(f"autostart={autostart}")
        return True

    def _apply_run_state(self, pool, state, msgs):
        """Start or stop the pool to match C(active)/C(inactive)."""
        active = bool(pool.isActive())

        if state == "active" and not active:
            if not self.module.check_mode:
                pool.create(0)
            msgs.append("started")
            return True

        if state == "inactive" and active:
            if not self.module.check_mode:
                pool.destroy()
            msgs.append("stopped")
            return True

        return False

    def _apply_refresh(self, pool, spec, msgs):
        """Rescan the pool's volumes when requested and the pool is active."""
        if not spec.get("refresh"):
            return False

        if not bool(pool.isActive()):
            return False

        if not self.module.check_mode:
            pool.refresh(0)
        msgs.append("refreshed")
        return True

    def _absent_one(self, pool):
        """Ensure the pool is stopped and undefined."""
        if pool is None:
            return dict(changed=False, msg="already absent")

        if self.module.check_mode:
            return dict(changed=True, msg="would undefine pool")

        if bool(pool.isActive()):
            pool.destroy()

        pool.undefine()

        return dict(changed=True, msg="undefined")

    # -- helpers -----------------------------------------------------------

    def _pool_facts(self, pool):
        """ """
        return dict(
            path=pool_target_path(pool.XMLDesc(0)),
            active=bool(pool.isActive()),
            autostart=bool(pool.autostart()),
            persistent=bool(pool.isPersistent()),
            uuid=pool.UUIDString(),
        )


def main():
    """ """
    pool_suboptions = dict(
        name=dict(type="str", required=True),
        state=dict(type="str", default="present", choices=["present", "active", "inactive", "absent"]),
        type=dict(type="str", default="dir", choices=["dir"]),
        target_path=dict(type="path", aliases=["path"]),
        mode=dict(type="str"),
        owner=dict(type="str"),
        group=dict(type="str"),
        uuid=dict(type="str"),
        autostart=dict(type="bool"),
        build=dict(type="bool", default=False),
        refresh=dict(type="bool", default=False),
    )

    args = dict(
        uri=dict(type="str", default="qemu:///system"),
        pools=dict(
            type="list",
            elements="dict",
            required=True,
            options=pool_suboptions,
        ),
    )

    module = AnsibleModule(
        argument_spec=args,
        supports_check_mode=True,
    )

    if not HAS_LIBVIRT:
        module.fail_json(
            msg=missing_required_lib("libvirt-python"),
            exception=LIBVIRT_IMPORT_ERROR,
        )

    try:
        p = LibvirtPool(module)
        result = p.run()
    except Exception as e:  # pragma: no cover - defensive
        module.fail_json(msg=f"unexpected error: {e}", exception=traceback.format_exc())

    module.exit_json(**result)


# import module snippets
if __name__ == "__main__":
    main()
